---
title: "03. Contrastive analysis. Excercises"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

3.1. Загрузите датасет по поэтам Серебряного века и их современникам
(silver_poems.csv). Проведите лемматизацию (с помощью mystem) и
токенизацию текстов. 

3.2. Выберите одного из поэтов и проведите контрастный анализ лексики
его стихов на фоне лексики всех остальных поэтов, включенных в
датасет, с помощью подхода simple maths Адама Килгариффа (+n). В
качестве констант для добавления к частотности используйте 1, 10, 100.
Как изменяется список наиболее характерных для выбранного поэта слов
при увеличении константы?

3.3. Повторите контрастный анализ из упражнения 3.2, на этот раз
используя в качестве меры значимости различий отношение правдоподобия
Даннинга. Обращайте внимание, что log likelihood — симметричная мера,
и она показывает как существенно более частотные, так и менее
частотные для данного автора лексические единицы. В чем результаты
сходны и в чем отличаются от результатов предыдущего упражнения?

3.4. Проверьте влияние параметров препроцессинга на результаты
контрастного анализа лексики выбранного поэта и их потенциальное
влияние на выводы из такого анализа. Для этого проведите серию
экспериментов с расчетом log likelihood при разных параметрах
препроцессинга. Попробуйте проварьировать следующие параметры:

* наличие/отсутствие лемматизации;
* удаление/сохранение стоп-слов;
* статический список стоп-слов stopwords("ru") / динамический список
  стоп-слов (вершина частотного списка);
* наличие/отсутствие порога отсечения по частотности.

Необходимо сформировать не менее трех различных комбинаций названных
выше параметров, провести обработку текстов с выбранным набором
параметров и сравнить результаты контрастного анализа. Насколько
изменяются результаты?

3.5. Повторите контрастный анализ лексики выбранного поэта, но
ограничьте рассмотрение только прилагательными. Дает ли такой подход
новую информацию о специфике стиля и содержания текстов данного поэта?

3.6.* Авторы статьи, на которой основан приведенный в лекции пример о
жутковатой стилистике «Макбета», придают большое значение обнаруженной
ими повышенной частотности определенного артикля в Макбете по
сравнению с творчеством Шекспира в целом. Можно ли утверждать, что это
стилистическая особенность именно Макбета? Сравните относительную
частотность определенного артикля в разных произведениях Шекспира с
его частотностью в Макбете. Какие выводы можно сделать из такого
сравнения?



