---
title: "04. Contrastive analysis continued. Excercises"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

4.1. Продолжите эксперименты по определению характерной лексики одного
    из поэтов Серебряного века. На этот раз в качестве меры
    используйте PMI по образцу, предложенному в лекции. В чем отличия
    и в чем сходства списка топ-30 наиболее характерных слов,
    выделенных с помощью PMI и log-likelihood?
    
4.2. Примените к результатам вычисления PMI фильтрацию по частотности
слов таким образом, чтобы выделить в списке более частотную и в то же
время характерную для поэта лексику. Позволяет ли такой список сделать
какие-то обобщения о стилистике или содержании произведений данного
поэта?

4.3. Используйте для извлечения характерной лексики выбранного поэта
метод weighted log-odds, реализованный в пакете tidylo. В чем его
результаты отличаются от результатов log-likelohood и PMI? 

4.4.* В конце примера, разобранного в рамках лекции (04pmi.Rmd), было
обнаружено, что наименьшее значение weighted log odds в референсном
корпусе (весь Шекспир, _кроме_ Макбета) получили исключительно самые
частотные слова. Как вы можете объяснить этот эффект? Можно ли из этих
данных сделать вывод, что самые частотные слова (стоп-слова) менее
характерны для Шекспира в целом, чем для Макбета?


